### ISSUE TITLE
Add option to include specific subfolders only

### ISSUE THREAD

**Issue by pgadjev-ingka** [simasbu/confluence-site-descriptor-action#85]
Hey,

Is it possible to add an option which tells which specific subfolders to be included in the site descriptor? So instead of creating a site descriptor for all subfolders we'd be able to create only delta updates. This scenario will be useful when we maintain a big folder of Confluence documentation pages and we'd like to update only the ones which have been actually changed.

```
- name: Generate delta update site.yaml
  uses: simasbu/confluence-site-descriptor-action@main
  with:
    localDirectory: "confluence"
    subFolders: ["help/troubleshooting/blue-moon", "features/blue-moon"]
    parentPageTitle: "Home"
    homePageTitle: "Hello world"
    spaceKey: "SPACE"
```

The `subFolders` could be empty indicating that all sub-folders will be included, otherwise only selected paths will be included. This new parameter could be filled automatically by calculating the paths based on Git commits.
